routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


Route::get('/booking', function () {
    return view('booking');
})->name('booking');


Route::get('/thanks', function () {
    return view('thanks');
})->name('thanks');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'LandingPageController@Landing');
Route::post('/store', 'LandingPageController@store')->name('store');


//Route::post('consultation_requests','App\Http\Controllers\Dashboard\Consultation_requestsController@store')->name('consultation_requests');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider','facebook|google|youtube');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider','facebook|google|youtube');

app/Role.php
<?php

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{

    protected $fillable = ['name'];


    //Attribute
//    public function getNameAttribute ($value){
//        return ucfirst($value);
//    }//end of getNameAttribute



    // Scopes -------------------------------------------
    public function scopeWhenSearch($query , $search){
        return $query->when($search ,function ($q) use ($search){
            return $q->where('name','like',"%$search%");
        });
    }//end of scopeWhenSearch

    public function scopeWhereRoleNot ($query , $role_name){
        return $query->whereNotIn('name' , (array)$role_name );
    }//end of scopeWhereRoleNot
}

app/Http/Controllers/Dashboard/BenfactorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BenefactorController extends Controller
{
    //
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
     public function __construct()
         {
             //Parent Path
             $this->path = "dashboard.categories.";

             //Permissions
            $this->middleware('permission:read_categories')->only(['index']);
            $this->middleware('permission:create_categories')->only(['create','store']);
            $this->middleware('permission:update_categories')->only(['edit','update']);
            $this->middleware('permission:delete_categories')->only(['destroy']);

         }

          public function index()
          {
              $categories = Category::WhenSearch(request()->search)->paginate(5);
              return view($this->path.'index',compact('categories'));
          }//end of index

          public function create()
          {
               return view($this->path.'create');
          }//end of create

          public function store(Request $request)
          {
              $request->validate([
                  'description' => 'required|unique:categories,description',
              ]);
              Category::create($request->all());
              session()->flash('success',__('site.DataAddSuccessfully'));
              return redirect()->route($this->path.'index');
          }//end of store

          public function show($id)
          {
              //
          }//end of show

          public function edit(Category $category)
          {
               return view($this->path.'create',compact('category'));
          }//end of edit

          public function update(Request $request, Category $category)
          {
              $request->validate([
                  'description' => 'required|unique:categories,description,'.$category->id,
              ]);
              $category->update($request->all());
              session()->flash('success',__('site.DataUpdatedSuccessfully'));
              return redirect()->route($this->path.'index');
          }//end of update

          public function destroy(Category $category)
          {
              $category->delete();
              session()->flash('success',__('site.DataDeletedSuccessfully'));
              return redirect()->route($this->path.'index');
          }//end of destroy
}

app/Http/Controllers/Dashboard/ClassificationController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ClassificationController extends Controller
{
    //
}

app/Http/Controllers/Dashboard/Consultation_requestsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Consultation_requests;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class Consultation_requestsController extends Controller
{
//    public function __construct()
//    {
//        //Parent Path
//        $this->path = "dashboard.consultation_requests.";
//
//        //Permissions
//        $this->middleware('permission:read_categories')->only(['index']);
//        $this->middleware('permission:create_categories')->only(['create','store']);
//        $this->middleware('permission:update_categories')->only(['edit','update']);
//        $this->middleware('permission:delete_categories')->only(['destroy']);
//
//    }
//
//    public function index()
//    {
//        $consultation_requests = Consultation_requests::orderBy('id', 'desc')->WhenSearch(request()->search)->paginate(5);
//        return view($this->path.'index',compact('consultation_requests'));
//    }//end of index
//
//    public function create()
//    {
//        return view($this->path.'create');
//    }//end of create
//
//    public function store(Request $request)
//    {
//        $request->validate([
//            'name' => 'required|unique:categories,name',
//        ]);
//        Consultation_requests::create($request->all());
//
//        session()->flash('success',__('site.DataAddSuccessfully'));
//        return back();
//    }//end of store
//
//    public function show($id)
//    {
//        //
//    }//end of show
//
//    public function edit(Consultation_requests $consultation_requests)
//    {
//        return view($this->path.'create',compact('consultation_requests'));
//    }//end of edit
//
//    public function update(Request $request, Consultation_requests $consultation_requests)
//    {
//        $request->validate([
//            'name' => 'required|unique:consultation_requests,name,'.$consultation_requests->id,
//        ]);
//        $consultation_requests->update($request->all());
//        session()->flash('success',__('site.DataUpdatedSuccessfully'));
//        return redirect()->route($this->path.'index');
//    }//end of update
//
//    public function destroy(Consultation_requests $consultation_request)
//    {
//        $consultation_request->delete();
//        session()->flash('success',__('site.DataDeletedSuccessfully'));
//        return redirect()->route($this->path.'index');
//    }//end of destroy
}

app/Http/Controllers/Dashboard/ContactUsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\ContactUs;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class   ContactUsController extends Controller
{
    public function __construct()
    {
        //Parent Path
        $this->path = "dashboard.contact_us.";

        //Permissions
        $this->middleware('permission:read_contact_us')->only(['index']);
        $this->middleware('permission:create_contact_us')->only(['create','store']);
        $this->middleware('permission:update_contact_us')->only(['edit','update']);
        $this->middleware('permission:delete_contact_us')->only(['destroy']);

    }

    public function index()
    {
        $contact_us = ContactUs::WhenSearch(request()->search)->OrderBy('id','desc')->paginate(5);
        return view($this->path.'index',compact('contact_us'));
    }//end of index

    public function create()
    {
        return view($this->path.'create');
    }//end of create

    public function store(Request $request)
    {
//        $request->validate([
//            'description' => 'required|unique:categories,description',
//        ]);
        ContactUs::create($request->all());
        session()->flash('success',__('site.DataAddSuccessfully'));
        return view('thanks');
    }//end of store

    public function edit(ContactUs $contact_u)
    {
        return view($this->path.'create',compact('contact_u'));
    }//end of edit

    public function update(Request $request, ContactUs $contact_u)
    {
//        $request->validate([
//            'description' => 'required|unique:categories,description,'.$contact_us->id,
//        ]);
        $contact_u->update($request->all());
        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(ContactUs $contact_u)
    {
        $contact_u->delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/NeedyController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Needy;
use Illuminate\Http\Request;

class NeedyController extends Controller
{
    public function __construct()
    {
        //Parent Path
        $this->path = "dashboard.needies.";

        //Permissions
        $this->middleware('permission:read_needies')->only(['index']);
        $this->middleware('permission:create_needies')->only(['create','store']);
        $this->middleware('permission:update_needies')->only(['edit','update']);
        $this->middleware('permission:delete_needies')->only(['destroy']);

    }

    public function index()
    {
        $needies = Needy::WhenSearch(request()->search)->paginate(5);
        return view($this->path.'index',compact('needies'));
    }//end of index

    public function create()
    {
        return view($this->path.'create');
    }//end of create

    public function store(Request $request)
    {
        $request->validate([
            'userName' => 'required|unique:needies,userName',
        ]);

//        $request->only('name','userName','phone','city','address','family_number','notes');
         $data = $request->all()->except(['id_photo','supply_card_photo']);
        dd($data);

        Needy::create($request->all());
        session()->flash('success',__('site.DataAddSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of store

    public function show($id)
    {
        //
    }//end of show

    public function edit(Needy $category)
    {
        return view($this->path.'create',compact('category'));
    }//end of edit

    public function update(Request $request, Needy $category)
    {
        $request->validate([
            'userName' => 'required|unique:needies,userName,'.$category->id,
        ]);
        $category->update($request->all());
        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(Needy $category)
    {
        $category->delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/RoleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public function __construct()
    {
        // Parent Path
        $this->path = "dashboard.roles.";

        //Permissions
        $this->middleware('permission:read_roles')->only(['index']);
        $this->middleware('permission:create_roles')->only(['create','store']);
        $this->middleware('permission:update_roles')->only(['edit','update']);
        $this->middleware('permission:delete_roles')->only(['destroy']);
    }

    public function index()
    {
        $roles = Role::WhereRoleNot(['super_admin','admin'])
            ->WhenSearch(request()->search)
            ->with('permissions')
            ->withCount('users')
            ->paginate(5);
        return view($this->path.'index',compact('roles'));
    }//end of index

    public function create()
    {
        return view($this->path.'create');
    }//end of create

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:roles,name',
            'permissions' => 'required|array|min:1',
        ]);
        $role = Role::create($request->all());
        $role->attachPermissions($request->permissions);

        session()->flash('success',__('site.DataAddSuccessfully'));
        return redirect()->route($this->path.'index');

    }//end of store

    public function edit(Role $role)
    {
        return view($this->path.'create',compact('role'));
    }//end of edit

    public function update(Request $request, Role $role)
    {
        $request->validate([
            'name' => 'required|unique:roles,name,'.$role->id,
            'permissions' => 'required|array|min:1',
        ]);
        $role->update($request->all());
        $role->syncPermissions($request->permissions);
        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(Role $role)
    {
        $role->delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/SettingController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct (){
        // Parent Path
        $this->path = "dashboard.settings.";
    }//end of


    public function Social_Login (){
        return view($this->path.'social_login');
    }//end of Social_Login

    public function Social_Links (){
        return view($this->path.'social_links');
    }//end of Social_Links

    public function store (Request $request){
        setting($request->all())->save();
        session()->flash('success',__('site.DataSavedSuccessfully'));
        return redirect()->back();

    }//end of
}

app/Http/Controllers/Dashboard/SubCategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\Http\Controllers\Controller;
use App\SubCategory;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{
//    public function __construct()
//    {
//        //Parent Path
//        $this->path = "dashboard.sub_categories.";
//
//        //Permissions
//        $this->middleware('permission:read_sub_categories')->only(['index']);
//        $this->middleware('permission:create_sub_categories')->only(['create','store']);
//        $this->middleware('permission:update_sub_categories')->only(['edit','update']);
//        $this->middleware('permission:delete_sub_categories')->only(['destroy']);
//
//    }
//
//    public function index()
//    {
//       $subCategories = SubCategory::WhenSearch(request()->search)
//           ->with('category')
//           ->paginate(5);
//        return view($this->path.'index',compact('subCategories'));
//    }//end of index
//
//    public function create()
//    {
//        $categories = Category::all();
//        return view($this->path.'create',compact('categories'));
//    }//end of create
//
//    public function store(Request $request)
//    {
//        $request->validate([
//            'name' => 'required|unique:sub_categories,name',
//            'category_id' => 'required|numeric'
//        ]);
//        SubCategory::create($request->all());
//        session()->flash('success',__('site.DataAddSuccessfully'));
//        return redirect()->route($this->path.'index');
//    }//end of store
//
//    public function edit(SubCategory $subCategory)
//    {
//        $categories = Category::all();
//        return view($this->path.'create',compact('categories','subCategory'));
//    }//end of edit
//
//    public function update(Request $request, SubCategory $subCategory)
//    {
//        $request->validate([
//            'name' => 'required|unique:sub_categories,name,'.$subCategory->id,
//        ]);
//        $subCategory->update($request->all());
//        session()->flash('success',__('site.DataUpdatedSuccessfully'));
//        return redirect()->route($this->path.'index');
//    }//end of update
//
//    public function destroy(SubCategory $subCategory)
//    {
//        $subCategory->delete();
//        session()->flash('success',__('site.DataDeletedSuccessfully'));
//        return redirect()->route($this->path.'index');
//    }//end of destroy
}

resources/views/dashboard/roles/create.blade.php
@extends('layouts.dashboard.app')

@section('content')
    <div class="app-title">
        <div>
            @if(isset($role)  )
                <h1>
                    <i class="fa fa-edit">
                        {{ __('site.UpdateRole')}}
                    </i>
               </h1>
            @else
                <h1>
                    <i class="fa fa-plus">
                      {{__('site.AddRole') }}
                    </i>
                </h1>
            @endif

        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-list"></i></li>
            <li class="breadcrumb-item"><a href="{{route('dashboard.welcome')}}">{{__('site.Dashboard')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('dashboard.roles.index')}}">{{__('site.Role')}}</a></li>
            @if(isset($role))
                <li class="breadcrumb-item">{{__('site.UpdateRole')}}</li>
            @else
                <li class="breadcrumb-item">{{__('site.AddRole')}}</li>
            @endif
        </ul>
    </div>

    <div class="tile mb-4">
        <div class="row">
            <div class="col-md-12">
             <form action="{{isset($role)?route('dashboard.roles.update',$role->id):route('dashboard.roles.store')}}" method="post">
                 @csrf
                 @if(isset($role))
                     @method('put')
                 @else
                     @method('post')
                 @endif

                 @include('dashboard.partials._errors')

                 <div class="form-group">
                     <label>{{__('site.name')}} :</label>
                     <input type="text" name="name" class="form-control" value="{{isset($role)?$role->name:""}}">
                 </div>

                 <div class="form-group">
                     <h4>Permission</h4>

                     <table class="table table-hover">
                         <thead>
                            <tr>
                                <th>#</th>
                                <th>Model</th>
                                <th>Permission</th>
                            </tr>
                         </thead>
                        <tbody>

                        @php
                            $models = ['users','roles','settings','contact_us' ,'patients' ,'patients_classification','describe_treatments','describe_treatments_for_nurse'];
                        @endphp

                        @foreach( $models as $index=>$model )
                            <tr>
                                <td width="10%">{{$index+1}}</td>
                                <td width="20%">{{ucfirst($model)}}</td>
                                <td width="100%">
                                    @php
                                       $permission_maps = ['create','read','update','delete'];
                                    @endphp

                                        <select name="permissions[]"  class="form-control select2" multiple>
                                            @foreach( $permission_maps as $permission_map )
                                                @if( isset($role) )
                                                    <option
                                                        value="{{$permission_map . '_' . $model}} "
                                                        {{$role->hasPermission($permission_map . '_' . $model)?'selected':''}}
                                                    >
                                                        {{ $permission_map}}
                                                    </option>
                                                @else
                                                    <option value="{{$permission_map . '_' . $model}}">{{ $permission_map}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>

                     </table>
                 </div>

                 <div class="form-group">
                     <button type="submit" class="btn btn-primary">
                         @if( isset($role) )
                             <i class="fa fa-edit"></i>
                             {{__('site.Update')}}
                         @else
                             <i class="fa fa-plus"></i>
                             {{__('site.Add')}}
                         @endif

                     </button>
                 </div>
             </form>

            </div>{{-- end-of-col-12 --}}
        </div>{{--end-of-row--}}


    </div>{{--end-of-tile mb-4--}}


@endsection

resources/views/dashboard/roles/index.blade.php
@extends('layouts.dashboard.app')

@section('content')
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list"></i> Roles</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{{route('dashboard.welcome')}}">Dashboard</a></li>
            <li class="breadcrumb-item">Roles</li>
        </ul>
    </div>

    <div class="tile mb-4">
        <div class="row">
            <div class="col-md-12">
                {{-- this form for Search button                --}}
                <form action="" >
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="text" name="search" autofocus class="form-control" placeholder="Search" value="{{request()->search}}">
                            </div>
                        </div>{{-- end-of-col-4 --}}


                        <div class="col-md-4">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i>Search</button>
                                @if(auth()->user()->hasPermission('create_roles'))
                                    <a href="{{route('dashboard.roles.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i>{{__('site.Add')}} </a>
                                @else
                                    <a href="#" disabled="" class="btn btn-primary"><i class="fa fa-plus"></i>{{__('site.Add')}} </a>
                                @endif
                            </div>
                        </div>{{-- end-of-col-4 --}}


                    </div>{{-- end-of-row --}}
                </form>{{-- end-of-form --}}

            </div>{{-- end-of-col-12 --}}
        </div>{{--end-of-row--}}

        <div class="row">
            <div class="col-md-12">
                <hr>
                @if($roles->count() > 0 )
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>{{__('site.name')}}</th>
                            <th>{{__('site.UsersCount')}}</th>
                            <th>{{__('site.permissions')}}</th>
                            <th  width="25%">{{__('site.action')}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($roles as $index=>$role)
                            <tr>
                                <td>{{++$index}}</td>
                                <td>{{$role->name}}</td>
                                <td>{{$role->users_count}}</td>
                                <td>
                                    @foreach( $role->permissions as $permission )
                                        <span style="display: inline-block" class="badge badge-primary">{{$permission->name}}</span>
                                    @endforeach</td>
                                <td>
                                    {{--Edit buttom--}}
                                    @if(auth()->user()->hasPermission('update_roles'))
                                        <a href="{{route('dashboard.roles.edit', $role->id)}}" class="btn btn-warning btn-sm"><i class="fa fa-edit">{{__('site.Edit')}}</i></a>
                                    @else
                                        <a href="#" class="btn btn-warning btn-sm"><i class="fa fa-edit">{{__('site.Edit')}}</i></a>
                                    @endif

                                    @if(auth()->user()->hasPermission('delete_roles'))
                                        <form action="{{route('dashboard.roles.destroy', $role->id)}}" method="post" style="display: inline-block">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger btn-sm delete"><i class="fa fa-trash"></i>Delete</button>
                                        </form>
                                    @else
                                        <a href="#" disabled="" class="btn btn-danger btn-sm"><i class="fa fa-edit">{{__('site.Delete')}}</i></a>
                                    @endif


                                </td>
                            </tr>
                        @endforeach

                        </tbody>

                    </table>
                    {{$roles->appends(request()->query())->links()}}
                @else
                    <h3 style="font-weight: 400; text-align: center"> No Record Found</h3>
                @endif
            </div>
        </div>
    </div>{{--end-of-tile mb-4--}}


@endsection